version: '3.8'
services:
  file-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/fileservice
      - REDIS_URL=redis://redis:6379
      - B2_APPLICATION_KEY_ID=${B2_APPLICATION_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./temp_uploads:/app/temp_uploads
  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fileservice
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
  
  celery:
    build: .
    command: celery -A app.tasks worker --loglevel=info 
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/fileservice
      - REDIS_URL=redis://redis:6379
      - B2_APPLICATION_KEY_ID=${B2_APPLICATION_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./temp_uploads:/app/temp_uploads

volumes:
  postgres_data: